import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Sidebar2 from "@/components/Sidebar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Practice | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar2>
          {children}
        </Sidebar2>
      </body>
    </html>
  );
}
